import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.nonparametric.smoothers_lowess import lowess
import os

"""
This program creates a csv file called exercise-model-data.csv
for the workout app to use to train its model.

exercise-model-data.csv contains 2 columns. The first 
is action which contains exercises like walk and the 
second is t_max_avg which is the highest 5 aT (m/s^2) values 
averaged for the action.

"""

"""
This function appends the actions and the t_max_avg 
to exercise-model-data.csv 
"""
def create_exercise_data(inputFiles,exercises_df):
    for file in inputFiles: 
        #print("Processing: ", file.name)
        df = pd.read_csv(file)
   
        t_max_avg = df.nlargest(5, 'aT (m/s^2)') 
        t_max_avg = t_max_avg['aT (m/s^2)'].mean()
        
        file = os.path.basename(file.name)
        file = ''.join([i for i in file if not i.isdigit()])
        action = file[:-4]
        exercises_df = exercises_df.append({'action': action,
                                            't_max_avg': t_max_avg}
                                             , ignore_index=True)

    return exercises_df

"""
Function reads in a folder containing the data files for accelerometer 
data generated by Physics Toolbox Sensor Suite and returns 
them in a list
"""
def readFiles():
     path = "rawData/"
     inputFiles = []
   
     for filename in os.listdir(path):
         #print(filename)
         file  = path + filename
         inputFiles.append(open(file))

     return inputFiles
        
def main():
    inputFiles = readFiles()
    exercises_df = pd.DataFrame(columns=['action', 't_max_avg'])
    exercises_df = create_exercise_data(inputFiles, exercises_df)
    #print(exercises_df.groupby(['action']).agg([('average','mean')]),"\n")
    print("exercise-model-data.csv created")
    
    exercises_df.to_csv("exercise-model-data.csv", index=False)     

if __name__=='__main__':
    main()
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
